import { StateTransition } from './StateTransition';
import Message from '../../enum/Message';
import Signature from '../../enum/Signature';
import S from '../../enum/ServerState';

export const v3Transitions: StateTransition[] = [
    { from: S.CONNECTED, message: Message.HELLO, response: Signature.SUCCESS, to: S.READY },
    { from: S.CONNECTED, message: Message.HELLO, response: Signature.FAILURE, to: S.DEFUNCT },
    { from: S.READY, message: Message.RUN, response: Signature.SUCCESS, to: S.STREAMING },
    { from: S.READY, message: Message.RUN, response: Signature.FAILURE, to: S.FAILED },
    { from: S.READY, message: Message.BEGIN, response: Signature.SUCCESS, to: S.TX_READY },
    { from: S.READY, message: Message.BEGIN, response: Signature.FAILURE, to: S.FAILED },
    { from: S.READY, message: Message.RESET, response: Signature.SUCCESS, to: S.READY },
    { from: S.READY, message: Message.RESET, response: Signature.FAILURE, to: S.DEFUNCT },
    { from: S.STREAMING, message: Message.PULL_ALL, response: Signature.SUCCESS, to: S.READY },
    { from: S.STREAMING, message: Message.PULL_ALL, response: Signature.FAILURE, to: S.FAILED },
    { from: S.STREAMING, message: Message.DISCARD_ALL, response: Signature.SUCCESS, to: S.READY },
    { from: S.STREAMING, message: Message.DISCARD_ALL, response: Signature.FAILURE, to: S.FAILED },
    { from: S.STREAMING, message: Message.RESET, response: Signature.SUCCESS, to: S.READY },
    { from: S.STREAMING, message: Message.RESET, response: Signature.FAILURE, to: S.DEFUNCT },
    { from: S.TX_READY, message: Message.RUN, response: Signature.SUCCESS, to: S.TX_STREAMING },
    { from: S.TX_READY, message: Message.RUN, response: Signature.FAILURE, to: S.FAILED },
    { from: S.TX_READY, message: Message.COMMIT, response: Signature.SUCCESS, to: S.READY },
    { from: S.TX_READY, message: Message.COMMIT, response: Signature.FAILURE, to: S.FAILED },
    { from: S.TX_READY, message: Message.ROLLBACK, response: Signature.SUCCESS, to: S.READY },
    { from: S.TX_READY, message: Message.ROLLBACK, response: Signature.FAILURE, to: S.FAILED },
    { from: S.TX_READY, message: Message.RESET, response: Signature.SUCCESS, to: S.READY },
    { from: S.TX_READY, message: Message.RESET, response: Signature.FAILURE, to: S.DEFUNCT },
    { from: S.TX_STREAMING, message: Message.PULL_ALL, response: Signature.SUCCESS, to: S.TX_STREAMING },
    { from: S.TX_STREAMING, message: Message.PULL_ALL, response: Signature.FAILURE, to: S.FAILED },
    { from: S.TX_STREAMING, message: Message.DISCARD_ALL, response: Signature.SUCCESS, to: S.TX_STREAMING },
    { from: S.TX_STREAMING, message: Message.DISCARD_ALL, response: Signature.FAILURE, to: S.FAILED },
    { from: S.TX_STREAMING, message: Message.RESET, response: Signature.SUCCESS, to: S.READY },
    { from: S.TX_STREAMING, message: Message.RESET, response: Signature.FAILURE, to: S.DEFUNCT },
    { from: S.FAILED, message: Message.RUN, response: Signature.IGNORED, to: S.FAILED },
    { from: S.FAILED, message: Message.PULL_ALL, response: Signature.IGNORED, to: S.FAILED },
    { from: S.FAILED, message: Message.DISCARD_ALL, response: Signature.IGNORED, to: S.FAILED },
    { from: S.FAILED, message: Message.RESET, response: Signature.SUCCESS, to: S.READY },
    { from: S.FAILED, message: Message.RESET, response: Signature.FAILURE, to: S.DEFUNCT },
    { from: S.INTERRUPTED, message: Message.RUN, response: Signature.IGNORED, to: S.INTERRUPTED },
    { from: S.INTERRUPTED, message: Message.PULL_ALL, response: Signature.IGNORED, to: S.INTERRUPTED },
    { from: S.INTERRUPTED, message: Message.DISCARD_ALL, response: Signature.IGNORED, to: S.INTERRUPTED },
    { from: S.INTERRUPTED, message: Message.BEGIN, response: Signature.IGNORED, to: S.INTERRUPTED },
    { from: S.INTERRUPTED, message: Message.COMMIT, response: Signature.IGNORED, to: S.INTERRUPTED },
    { from: S.INTERRUPTED, message: Message.ROLLBACK, response: Signature.IGNORED, to: S.INTERRUPTED },
    { from: S.INTERRUPTED, message: Message.RESET, response: Signature.SUCCESS, to: S.READY },
    { from: S.INTERRUPTED, message: Message.RESET, response: Signature.FAILURE, to: S.DEFUNCT },
];
