name: Client test with NornicDB

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]

jobs:
  nornicdb-tests:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    name: Run Jest tests

    services:
      nornicdb:
        image: timothyswt/nornicdb-amd64-cpu:latest
        ports:
          - 7687:7687
          - 7474:7474
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: npm install
        run: npm ci

      - name: jest run test
        env:
          BOLT_AUTH_SCHEME: none
          BOLT_USER: ''
          BOLT_PASSWORD: ''
          BOLT_VERSION: '4.4.4'
        run: npm run test:client
